server:
  port: 8086
spring:
  application:
    name: rbd-service
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/osp?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 30000
      #事务查询超时时间
      transaction-query-timeout: 30000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,config

  jpa:
    open-in-view: false

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML


mybatis-plus:
  type-aliases-package: cn.seamew.rbd
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml


# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Sans-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index,/login/**,/favicon.ico